name: Deploy to VPS Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Łączenie z serwerem i restart Dockera
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # 1. Wejście do poprawnego folderu z projektem
            cd /home/mateusz/hw_app
            
            # 2. Pobranie najnowszego kodu z gałęzi production
            git pull origin production
            
            # 3. Przebudowanie i uruchomienie Dockera
            docker compose up -d --build
